// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvmyzydnunhhaqpxfmdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2bXl6eWRudW5oaGFxcHhmbWRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NjYyMzYsImV4cCI6MjA3MDM0MjIzNn0.ioY4rV0DLH8fSjBx0CEW6VSVnCY3AI1YeEjsKsILc-s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});